/* 
Abcedi Ilacas
Lab 04
DBS211-NBB
138180211
*/

SET AUTOCOMMIT ON;

/* 1 */
/*ANSI-89*/
SELECT RC.CONTACTFIRSTNAME,
    RC.CONTACTLASTNAME,
    RC.SALESREPEMPLOYEENUMBER,
    RE.EMPLOYEENUMBER,
    RE.FIRSTNAME,
    RE.LASTNAME,
    RO.CITY,
    RO.PHONE,
    RO.POSTALCODE
FROM RETAILCUSTOMERS RC,
    RETAILEMPLOYEES RE,
    RETAILOFFICES RO
WHERE RC.COUNTRY = 'Singapore'
    AND RC.SALESREPEMPLOYEENUMBER = RE.EMPLOYEENUMBER(+)
    AND RE.OFFICECODE = RO.OFFICECODE(+);
/*ANSI-92*/
SELECT RC.CONTACTFIRSTNAME,
    RC.CONTACTLASTNAME,
    RC.SALESREPEMPLOYEENUMBER,
    RE.EMPLOYEENUMBER,
    RE.FIRSTNAME,
    RE.LASTNAME,
    RO.CITY,
    RO.PHONE,
    RO.POSTALCODE
FROM RETAILCUSTOMERS RC
LEFT JOIN RETAILEMPLOYEES RE ON RC.SALESREPEMPLOYEENUMBER = RE.EMPLOYEENUMBER
LEFT JOIN RETAILOFFICES RO ON RE.OFFICECODE = RO.OFFICECODE
WHERE RC.COUNTRY = 'Singapore';
    
/* 2 */
SELECT RC.CUSTOMERNUMBER,
    RC.CUSTOMERNAME,
    RC.COUNTRY,
    TO_CHAR(rp.PAYMENTDATE, 'DD/MM/YYYY') AS "Payment Date(DD/MM/YYYY)",
    RP.AMOUNT
FROM RETAILCUSTOMERS RC
JOIN RETAILPAYMENTS RP ON RC.CUSTOMERNUMBER = RP.CUSTOMERNUMBER
WHERE RC.COUNTRY = 'USA'
ORDER BY RC.CUSTOMERNUMBER;

/* 3 */
SELECT RC.CUSTOMERNUMBER,
    RC.CUSTOMERNAME,
    RP.AMOUNT
FROM RETAILCUSTOMERS RC
JOIN RETAILPAYMENTS RP ON RC.CUSTOMERNUMBER = RP.CUSTOMERNUMBER
WHERE RC.COUNTRY = 'Canada'
ORDER BY RC.CUSTOMERNUMBER;

/* 4 */
SELECT RO.CUSTOMERNUMBER,
    OD.QUANTITYORDERED,
    OD.PRICEEACH,
    RC.CUSTOMERNAME,
    RC.COUNTRY
FROM RETAILORDERS RO
JOIN ORDERDETAILS OD ON RO.ORDERNUMBER = OD.ORDERNUMBER
JOIN RETAILCUSTOMERS RC ON RO.CUSTOMERNUMBER = RC.CUSTOMERNUMBER
WHERE RC.COUNTRY = 'Denmark'
AND RO.STATUS = 'Shipped';

/* 5 */
DROP VIEW vwProductOrder;
CREATE VIEW vwProductOrder AS
SELECT RPR.PRODUCTCODE,
    RPR.PRODUCTNAME,
    RPR.MSRP,
    RPR.BUYPRICE,
    OD.QUANTITYORDERED,
    OD.PRICEEACH,
    (OD.QUANTITYORDERED * OD.PRICEEACH) AS TOTALPRICE
FROM RETAILPRODUCTS RPR
JOIN ORDERDETAILS OD ON RPR.PRODUCTCODE = OD.PRODUCTCODE;

SELECT * FROM vwProductOrder;

/* 6 */
SELECT PRODUCTNAME,
    BUYPRICE,
    QUANTITYORDERED,
    PRICEEACH,
    TOTALPRICE
FROM vwProductOrder
WHERE BUYPRICE BETWEEN 30 AND 40
AND PRODUCTCODE LIKE 'S32%'
ORDER BY PRODUCTNAME,
    BUYPRICE;

/* 7 */
SELECT RC.CUSTOMERNUMBER,
    RC.CONTACTFIRSTNAME,
    RC.CONTACTLASTNAME,
    RC.PHONE,
    RC.CREDITLIMIT
FROM RETAILCUSTOMERS RC
LEFT JOIN RETAILORDERS RO ON RC.CUSTOMERNUMBER = RO.CUSTOMERNUMBER
WHERE RO.ORDERNUMBER IS NULL
ORDER BY RC.CUSTOMERNUMBER;

/* 8 */
DROP VIEW vwEmployeeManager;
CREATE VIEW vwEmployeeManager AS
SELECT RE.EMPLOYEENUMBER AS EMPLOYEENUMBER,
    RE.FIRSTNAME AS EMPLOYEEFIRSTNAME,
    RE.LASTNAME AS EMPLOYEELASTNAME,
    RM.EMPLOYEENUMBER AS MANAGERNUMBER,
    RM.FIRSTNAME AS MANAGERFIRSTNAME,
    RM.LASTNAME AS MANAGERLASTNAME
FROM RETAILEMPLOYEES RE
LEFT JOIN RETAILEMPLOYEES RM ON RE.REPORTSTO = RM.EMPLOYEENUMBER
ORDER BY RE.EMPLOYEENUMBER;

SELECT * FROM vwEmployeeManager;

/* 9 */
CREATE OR REPLACE VIEW vwEmployeeManager AS
SELECT RE.EMPLOYEENUMBER AS EMPLOYEENUMBER,
    RE.FIRSTNAME AS EMPLOYEEFIRSTNAME,
    RE.LASTNAME AS EMPLOYEELASTNAME,
    RM.EMPLOYEENUMBER AS MANAGERNUMBER,
    RM.FIRSTNAME AS MANAGERFIRSTNAME,
    RM.LASTNAME AS MANAGERLASTNAME
FROM RETAILEMPLOYEES RE
JOIN RETAILEMPLOYEES RM ON RE.REPORTSTO = RM.EMPLOYEENUMBER
ORDER BY RE.EMPLOYEENUMBER;

SELECT * FROM vwEmployeeManager;
/* 10 */
DROP VIEW vwProductOrder;
DROP VIEW vwEmployeeManager;