/* 
Abcedi Ilacas
Lab 04
DBS211-NBB
138180211
*/

SET AUTOCOMMIT ON;

/* 1 */
SELECT RETAILCUSTOMERS.CONTACTFIRSTNAME,
    RETAILCUSTOMERS.CONTACTLASTNAME,
    RETAILCUSTOMERS.SALESREPEMPLOYEENUMBER,
    RETAILEMPLOYEES.EMPLOYEENUMBER,
    RETAILEMPLOYEES.FIRSTNAME,
    RETAILEMPLOYEES.LASTNAME,
    RETAILEMPLOYEES.OFFICECODE,
    RETAILOFFICES.CITY,
    RETAILOFFICES.PHONE,
    RETAILOFFICES.POSTALCODE
FROM RETAILCUSTOMERS,
    RETAILEMPLOYEES,
    RETAILOFFICES
WHERE RETAILCUSTOMERS.COUNTRY = 'Singapore' AND
    RETAILCUSTOMERS.SALESREPEMPLOYEENUMBER = RETAILEMPLOYEES.EMPLOYEENUMBER;
    
/* 2 */
SELECT RETAILCUSTOMERS.CUSTOMERNUMBER,
    RETAILCUSTOMERS.CUSTOMERNAME,
    RETAILCUSTOMERS.COUNTRY,
    RETAILPAYMENTS.PAYMENTDATE AS "YY-MM-DD PAYMENTDATE",
    RETAILPAYMENTS.AMOUNT
FROM RETAILCUSTOMERS,
    RETAILPAYMENTS
WHERE RETAILCUSTOMERS.COUNTRY = 'USA'
ORDER BY RETAILCUSTOMERS.CUSTOMERNUMBER;

/* 3 */

