/* Abcedi Ilacas
   138180211
   25/01/2024
   Lab 03       */

SET AUTOCOMMIT ON;

/* 1) */

SELECT * FROM RETAILPAYMENTS
FETCH NEXT 10 ROWS ONLY;

/* 2) */

SELECT FIRSTNAME, LASTNAME, CONCAT(FIRSTNAME, LASTNAME) AS fullname, EMAIL FROM RETAILEMPLOYEES
WHERE OFFICECODE = '6';

/* 3) */

SELECT CUSTOMERNUMBER, CUSTOMERNAME, CONTACTFIRSTNAME, CONTACTLASTNAME, PHONE FROM RETAILCUSTOMERS
WHERE CITY = 'Paris';

/* 4) */

SELECT CUSTOMERNUMBER, CUSTOMERNAME, CONCAT(CONTACTLASTNAME, CONTACTFIRSTNAME) AS fullname, PHONE FROM RETAILCUSTOMERS
WHERE Country = 'Canada';

/* 5) */

SELECT CUSTOMERNUMBER FROM RETAILCUSTOMERS
WHERE CREDITLIMIT != '0';

/* 6) */

SELECT CUSTOMERNUMBER, CHECKNUMBER, AMOUNT FROM RETAILPAYMENTS
WHERE AMOUNT NOT BETWEEN 30000 AND 65000
ORDER BY AMOUNT DESC;

/* 7) */

SELECT * FROM RETAILORDERS
WHERE STATUS = 'Cancelled';

/* 8) */

SELECT PRODUCTCODE, PRODUCTNAME, BUYPRICE, MSRP,
(MSRP - BUYPRICE) AS markup, ROUND(100 * (MSRP - BUYPRICE) / BUYPRICE, 1) AS PERCMARKUP FROM RETAILPRODUCTS;

/* 9) */ 

SELECT * FROM RETAILPRODUCTS
WHERE UPPER(PRODUCTNAME) LIKE '%CO%';

/* 10) */

SELECT * FROM RETAILCUSTOMERS
WHERE (LOWER(CONTACTFIRSTNAME) LIKE 's%' AND
LOWER(CONTACTFIRSTNAME) LIKE '%e%');

