-- MS3
-- Abcedi Ilacas, Sarah Mathew and Wing Wong
-- Group 15
-- DBS211-NBB
-- 04-19-24

--Creation Script: 
--A single SQL file providing the scripting to create all the tables, 
--including allconstraints and features as designed in the ERD and data dictionary.

SET AUTOCOMMIT ON;

-- SUPPLIER INFORMATION TABLE
CREATE TABLE SUPPLIERINFORMATION (
    SUPPLIERID NUMBER(4) PRIMARY KEY,
    SUPPLIERNAME VARCHAR2(30) NOT NULL,
    ADDRESS VARCHAR2(80) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    PHONE NUMBER NOT NULL CHECK (PHONE BETWEEN 2000000000 AND 9999999999),
    CONTACTPERSON VARCHAR2(20) NOT NULL
);

-- STORE LOCATIONS TABLE
CREATE TABLE STORELOCATIONS (
    STOREID NUMBER(3) PRIMARY KEY,
    ADDRESS VARCHAR2(80),
    PHONENUMBER NUMBER NOT NULL CHECK (PHONENUMBER BETWEEN 2000000000 AND 9999999999)
);

-- CUSTOMER INFORMATION TABLE
CREATE TABLE CUSTOMERINFORMATION (
    CUSTOMERID NUMBER(5) PRIMARY KEY,
    FIRSTNAME VARCHAR2(25) NOT NULL,
    LASTNAME VARCHAR2(25) NOT NULL,
    DATEOFBIRTH DATE,
    EMAIL VARCHAR2(80) NOT NULL,
    PHONENUMBER NUMBER NOT NULL CHECK (PHONENUMBER BETWEEN 2000000000 AND 9999999999)
);

-- EMPLOYEE INFORMATION TABLE
CREATE TABLE EMPLOYEEINFORMATION (
    EMPLOYEEID NUMBER(4) PRIMARY KEY,
    TITLE VARCHAR2(25) NOT NULL,
    STOREID NUMBER(3) NOT NULL,
    FIRSTNAME VARCHAR2(25) NOT NULL,
    LASTNAME VARCHAR2(25) NOT NULL,
    ADDRESS VARCHAR2(80) NOT NULL,
    EMAIL VARCHAR2(80) NOT NULL,
    PHONENUMBER NUMBER NOT NULL CHECK (PHONENUMBER BETWEEN 2000000000 AND 9999999999),
    FOREIGN KEY (STOREID) REFERENCES STORELOCATIONS(STOREID)
);

-- ITEM DESCRIPTIONS TABLE
CREATE TABLE ITEMDESCRIPTIONS (
    ITEMID NUMBER(5) PRIMARY KEY,
    COLOUR VARCHAR2(25),
    SPECIFICATIONS VARCHAR2(50),
    SUPPLIERID NUMBER(4) NOT NULL,
    FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIERINFORMATION(SUPPLIERID)
);

-- INVENTORY LEVELS TABLE
CREATE TABLE INVENTORYLEVELS (
    ITEMID NUMBER(5),
    STOREID NUMBER(3),
    QUANTITY NUMBER(4) NOT NULL CHECK (QUANTITY BETWEEN 1 AND 9999),
    AISLE NUMBER(2) NOT NULL CHECK (AISLE BETWEEN 1 AND 99),
    PRIMARY KEY (ITEMID, STOREID),
    FOREIGN KEY (ITEMID) REFERENCES ITEMDESCRIPTIONS(ITEMID),
    FOREIGN KEY (STOREID) REFERENCES STORELOCATIONS(STOREID)
);

-- PURCHASE HISTORY TABLE
CREATE TABLE PURCHASEHISTORY (
    PURCHASEID NUMBER(5) PRIMARY KEY,
    CUSTOMERID NUMBER(5) NOT NULL,
    STOREID NUMBER(3) NOT NULL,
    ITEMID NUMBER(5) NOT NULL,
    DATEOFPURCHASE DATE NOT NULL,
    QUANTITY NUMBER(3) NOT NULL CHECK (QUANTITY BETWEEN 1 AND 999),
    PRICEOFEACH NUMBER(4,2) NOT NULL CHECK (PRICEOFEACH BETWEEN 1 AND 9999),
    EMPLOYEEID NUMBER(5) NOT NULL,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERINFORMATION(CUSTOMERID),
    FOREIGN KEY (STOREID) REFERENCES STORELOCATIONS(STOREID),
    FOREIGN KEY (ITEMID) REFERENCES ITEMDESCRIPTIONS(ITEMID),
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEINFORMATION(EMPLOYEEID)
);

-- EMPLOYEE PERFORMANCE TABLE
CREATE TABLE EMPLOYEEPERFORMANCE (
    EMPLOYEEREVIEWID NUMBER(4) PRIMARY KEY,
    EMPLOYEEID NUMBER(4) NOT NULL,
    RATINGVALUE NUMBER(1) NOT NULL CHECK (RATINGVALUE BETWEEN 1 AND 5),
    REVIEW VARCHAR2(50) NOT NULL,
    REVIEWDATE DATE NOT NULL,
    FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEEINFORMATION(EMPLOYEEID)
);
