// MS3
// Abcedi Ilacas, Sarah Mathew and Wing Wong
// Group 15
// DBS211-NBB
// 04-19-24

// Sample Data Script: 
//A single SQL file providing the scripting to insert sample data into all tables.  

// CUSTOMERINFORMATION DATA
INSERT ALL
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(1, 'John', 'Smith', 'john.smith@example.com', '3234567890', TO_DATE('1985/03/12', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(2, 'Alice', 'Johnson', 'alice.johnson@example.com', '2345678901', TO_DATE('1990/07/25', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(3, 'David', 'Williams', 'david.williams@example.com', '3456789012', TO_DATE('1982/11/05', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(4, 'Mary', 'Brown', 'mary.brown@example.com', '4567890123', TO_DATE('1978/09/18', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(5, 'Jessica', 'Davis', 'jessica.davis@example.com', '5678901234', TO_DATE('1989/04/30', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(6, 'Michael', 'Miller', 'michael.miller@example.com', '6789012345', TO_DATE('1980/01/15', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(7, 'Jennifer', 'Wilson', 'jennifer.wilson@example.com', '7890123456', TO_DATE('1995/06/23', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(8, 'Christopher', 'Moore', 'christopher.moore@example.com', '8901234567', TO_DATE('1984/08/07', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(9, 'Amanda', 'Taylor', 'amanda.taylor@example.com', '9012345678', TO_DATE('1987/02/28', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(10, 'Matthew', 'Anderson', 'matthew.anderson@example.com', '4123456789', TO_DATE('1975/12/10', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(11, 'Sarah', 'Martinez', 'sarah.martinez@example.com', '4234501234', TO_DATE('1986/10/03', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(12, 'Ryan', 'Hernandez', 'ryan.hernandez@example.com', '2345612345', TO_DATE('1992/05/27', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(13, 'Emily', 'Young', 'emily.young@example.com', '3456723456', TO_DATE('1981/03/08', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(14, 'Daniel', 'Lopez', 'daniel.lopez@example.com', '4567834567', TO_DATE('1979/11/22', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(15, 'Jessica', 'Gonzalez', 'jessica.gonzalez@example.com', '5678945678', TO_DATE('1993/08/14', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(16, 'Andrew', 'Perez', 'andrew.perez@example.com', '6789056789', TO_DATE('1983/04/17', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(17, 'Emma', 'Rodriguez', 'emma.rodriguez@example.com', '7890167890', TO_DATE('1988/01/20', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(18, 'Jacob', 'Cook', 'jacob.cook@example.com', '8901278901', TO_DATE('1985/09/05', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(19, 'Olivia', 'James', 'olivia.james@example.com', '9012309012', TO_DATE('1977/07/02', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(20, 'William', 'Collins', 'william.collins@example.com', '4123410123', TO_DATE('1991/06/09', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(21, 'Sophia', 'Stewart', 'sophia.stewart@example.com', '5234521234', TO_DATE('1976/02/13', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(22, 'James', 'Lee', 'james.lee@example.com', '2345632345', TO_DATE('1989/10/28', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(23, 'Isabella', 'Harris', 'isabella.harris@example.com', '3456743456', TO_DATE('1980/12/21', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(24, 'Alexander', 'Clark', 'alexander.clark@example.com', '4567854567', TO_DATE('1974/06/16', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(25, 'Mia', 'Lewis', 'mia.lewis@example.com', '5678965678', TO_DATE('1994/04/03', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(26, 'Benjamin', 'Walker', 'benjamin.walker@example.com', '6789076789', TO_DATE('1982/11/30', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(27, 'Charlotte', 'Young', 'charlotte.young@example.com', '7890187890', TO_DATE('1987/08/26', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(28, 'Ethan', 'Hall', 'ethan.hall@example.com', '8901298901', TO_DATE('1979/05/19', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(29, 'Amelia', 'Allen', 'amelia.allen@example.com', '9012309012', TO_DATE('1983/03/22', 'YYYY/MM/DD'))
INTO CUSTOMERINFORMATION (CUSTOMERID, FIRSTNAME, LASTNAME, EMAIL, PHONENUMBER, DATEOFBIRTH) VALUES
(30, 'Liam', 'Adams', 'liam.adams@example.com', '6123410123', TO_DATE('1990/01/07', 'YYYY/MM/DD'))
SELECT * FROM dual;

// STORELOCATIONS DATA
INSERT ALL
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(51, '123 Main Street, Toronto, ON', 6135555678)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(52, '456 Elm Street, Ottawa, ON', 6135559876)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(53, '789 Oak Street, London, ON', 5195554567)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(54, '321 Pine Street, Hamilton, ON', 9055552345)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(55, '654 Maple Street, Mississauga, ON', 9055556789)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(56, '987 Cedar Street, Brampton, ON', 9055553456)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(57, '135 Birch Street, Markham, ON', 9055557890)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(58, '246 Elmwood Street, Vaughan, ON', 9055552345)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(59, '357 Oakwood Street, Richmond Hill, ON', 9055556789)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(60, '468 Maplewood Street, Windsor, ON', 5195551234)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(61, '579 Cedarwood Street, Kitchener, ON', 5195555678)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(62, '680 Pinecrest Street, Cambridge, ON', 5195559876)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(63, '791 Birchwood Street, Waterloo, ON', 5195554567)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(64, '802 Oakwood Street, Guelph, ON', 5195557890)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(65, '913 Elmwood Street, Barrie, ON', 7055552345)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(66, '124 Maplecrest Street, Kingston, ON', 6135556789)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(67, '235 Cedarcrest Street, Thunder Bay, ON', 8075553456)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(68, '346 Pinewood Street, Sudbury, ON', 7055557890)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(69, '457 Birchwood Street, Burlington, ON', 9055551234)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(70, '568 Oakcrest Street, Milton, ON', 9055555678)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(71, '679 Elmcrest Street, Oakville, ON', 9055559876)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(72, '780 Maplewood Street, St. Catharines, ON', 9055554567)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(73, '891 Pinecrest Street, Niagara Falls, ON', 9055557890)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(74, '902 Cedarwood Street, Peterborough, ON', 7055552345)
INTO STORELOCATIONS (STOREID, ADDRESS, PHONENUMBER) VALUES
(75, '113 Birchcrest Street, Sarnia, ON', 5195556789)
SELECT * FROM dual;

// EMPLOYEEINFORMATION DATA
INSERT ALL
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(101, 'Cashier', 57, 'Alice', 'Johnson', '200 Elm Street, Ottawa, ON', 'alice.johnson@example.com', 2345678901)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(102, 'Store Manager', 53, 'David', 'Williams', '300 Oak Street, Mississauga, ON', 'david.williams@example.com', 3456789012)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(103, 'Sales Associate', 65, 'Mary', 'Brown', '400 Maple Avenue, Brampton, ON', 'mary.brown@example.com', 4567890123)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(104, 'Cashier', 62, 'Jessica', 'Davis', '500 Bay Street, Hamilton, ON', 'jessica.davis@example.com', 5678901234)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(105, 'Sales Associate', 67, 'Michael', 'Miller', '600 Queen Street, London, ON', 'michael.miller@example.com', 6789012345)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(106, 'Cashier', 61, 'Jennifer', 'Wilson', '700 Yonge Street, Markham, ON', 'jennifer.wilson@example.com', 7890123456)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(107, 'Sales Manager', 71, 'Christopher', 'Moore', '800 Dundas Street, Richmond Hill, ON', 'christopher.moore@example.com', 8901234567)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(108, 'Cashier', 68, 'Amanda', 'Taylor', '900 Wellington Street, Oakville, ON', 'amanda.taylor@example.com', 9012345678)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(109, 'Sales Associate', 73, 'Matthew', 'Anderson', '1000 Bathurst Street, Kingston, ON', 'matthew.anderson@example.com', 6123556789)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(110, 'Store Manager', 52, 'Sarah', 'Martinez', '1100 St. Clair Avenue, Oshawa, ON', 'sarah.martinez@example.com', 6234666123)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(111, 'Cashier', 69, 'Ryan', 'Hernandez', '1200 Danforth Road, Vaughan, ON', 'ryan.hernandez@example.com', 2345666234)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(112, 'Sales Associate', 63, 'Emily', 'Young', '1300 Lawrence Avenue, Burlington, ON', 'emily.young@example.com', 3455523456)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(113, 'Cashier', 72, 'Daniel', 'Lopez', '1400 Sheppard Avenue, Pickering, ON', 'daniel.lopez@example.com', 4567834996)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(114, 'Sales Manager', 54, 'Jessica', 'Gonzalez', '1500 Finch Avenue, Ajax, ON', 'jessica.gonzalez@example.com', 5688894567)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(115, 'Cashier', 70, 'Andrew', 'Perez', '1600 Keele Street, Whitby, ON', 'andrew.perez@example.com', 6789056888)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(116, 'Sales Associate', 56, 'Emma', 'Rodriguez', '1700 Eglinton Avenue, Milton, ON', 'emma.rodriguez@example.com', 7890167080)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(117, 'Cashier', 74, 'Jacob', 'Cook', '1800 Yonge Street, Halton Hills, ON', 'jacob.cook@example.com', 8901468901)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(118, 'Sales Manager', 59, 'Olivia', 'James', '1900 Dufferin Street, Newmarket, ON', 'olivia.james@example.com', 9012309462)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(119, 'Cashier', 75, 'William', 'Collins', '2000 Bayview Avenue, Ajax, ON', 'william.collins@example.com', 6123410123)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(120, 'Sales Associate', 51, 'Sophia', 'Stewart', '2100 Lawrence Avenue, Richmond Hill, ON', 'sophia.stewart@example.com', 6293821234)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(121, 'Cashier', 66, 'James', 'Lee', '2200 Yonge Street, Oakville, ON', 'james.lee@example.com', 2343052345)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(122, 'Store Manager', 75, 'Isabella', 'Harris', '2300 St. Clair Avenue, Burlington, ON', 'isabella.harris@example.com', 3456798356)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(123, 'Sales Associate', 60, 'Alexander', 'Clark', '2400 Sheppard Avenue, Markham, ON', 'alexander.clark@example.com', 4563884567)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(124, 'Cashier', 55, 'Mia', 'Lewis', '2500 Danforth Avenue, Vaughan, ON', 'mia.lewis@example.com', 5629965678)
INTO EMPLOYEEINFORMATION (EMPLOYEEID, TITLE, STOREID, FIRSTNAME, LASTNAME, ADDRESS, EMAIL, PHONENUMBER) VALUES
(125, 'Sales Manager', 64, 'John', 'Smith', '150 Main Street, Toronto, ON', 'john.smith@example.com', 2234567890)

SELECT * FROM dual;

// SUPPLIERINFORMATION DATA
INSERT ALL
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(151, 'ABC Electronics', '123 Main Street, Toronto, ON', 'info@abcelectronics.com', 4165551234, 'John Doe')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(152, 'DEF Supplies', '456 Elm Street, Ottawa, ON', 'sales@defsupplies.com', 6135555678, 'Jane Smith')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(153, 'GHI Manufacturing', '789 Oak Street, London, ON', 'support@ghimanufacturing.com', 5195559876, 'Michael Johnson')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(154, 'JKL Technologies', '321 Pine Street, Hamilton, ON', 'info@jkltech.com', 9055554567, 'Sarah Wilson')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(155, 'MNO Solutions', '654 Maple Street, Mississauga, ON', 'sales@mnosolutions.com', 9055557890, 'Chris Lee')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(156, 'PQR Industries', '987 Cedar Street, Brampton, ON', 'info@pqrindustries.com', 9055552345, 'Emily Brown')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(157, 'STU Enterprises', '135 Birch Street, Markham, ON', 'sales@stuenterprises.com', 9055556789, 'David Taylor')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(158, 'VWX Corporation', '246 Elmwood Street, Vaughan, ON', 'support@vwxcorp.com', 9055553456, 'Emma Johnson')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(159, 'YZ Tech', '357 Oakwood Street, Richmond Hill, ON', 'info@yztech.com', 9055557890, 'Alex Miller')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(160, 'LMN Supplies', '468 Maplewood Street, Windsor, ON', 'sales@lmnsupplies.com', 5195551234, 'Olivia Wilson')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(161, 'OPQ Manufacturing', '579 Cedarwood Street, Kitchener, ON', 'info@opqmanufacturing.com', 5195555678, 'Daniel White')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(162, 'RST Technologies', '680 Pinecrest Street, Cambridge, ON', 'sales@rsttech.com', 5195559876, 'Sophia Martinez')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(163, 'UVW Solutions', '791 Birchwood Street, Waterloo, ON', 'support@uwvsolutions.com', 5195554567, 'Ethan Lee')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(164, 'XYZ Suppliers', '802 Oakwood Street, Guelph, ON', 'info@xyzsuppliers.com', 5195557890, 'Isabella Anderson')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(165, 'ABC Electronics', '913 Elmwood Street, Barrie, ON', 'sales@abcelectronics.com', 7055552345, 'Noah Thompson')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(166, 'DEF Supplies', '124 Maplecrest Street, Kingston, ON', 'info@defsupplies.com', 6135556789, 'Ava Garcia')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(167, 'GHI Manufacturing', '235 Cedarcrest Street, Thunder Bay, ON', 'support@ghimanufacturing.com', 8075553456, 'Liam Brown')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(168, 'JKL Technologies', '346 Pinewood Street, Sudbury, ON', 'info@jkltech.com', 7055557890, 'Mia Wilson')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(169, 'MNO Solutions', '457 Birchwood Street, Burlington, ON', 'sales@mnosolutions.com', 9055551234, 'Lucas Taylor')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(170, 'PQR Industries', '568 Oakcrest Street, Milton, ON', 'info@pqrindustries.com', 9055555678, 'Sophia Martinez')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(171, 'STU Enterprises', '679 Elmcrest Street, Oakville, ON', 'sales@stuenterprises.com', 9055559876, 'Jackson Garcia')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(172, 'VWX Corporation', '780 Maplewood Street, St. Catharines, ON', 'support@vwxcorp.com', 9055554567, 'Olivia Thompson')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(173, 'YZ Tech', '891 Pinecrest Street, Niagara Falls, ON', 'info@yztech.com', 9055557890, 'Liam Brown')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(174, 'LMN Supplies', '902 Cedarwood Street, Peterborough, ON', 'sales@lmnsupplies.com', 7055552345, 'Ava Garcia')
INTO SUPPLIERINFORMATION (SUPPLIERID, SUPPLIERNAME, ADDRESS, EMAIL, PHONE, CONTACTPERSON) VALUES
(175, 'OPQ Manufacturing', '113 Birchcrest Street, Sarnia, ON', 'info@opqmanufacturing.com', 5195556789, 'Ethan Lee')
SELECT * FROM dual;


// ITEMDESCRIPTIONS DATA
INSERT ALL
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(201, 'Red', 'Wireless Bluetooth Earphones', 160)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(202, 'Blue', 'Gaming Mouse with RGB Lighting', 160)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(203, 'Green', 'Stainless Steel Water Bottle', 160)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(204, 'Black', 'Portable External Hard Drive', 161)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(205, 'White', 'Smart LED Light Bulb', 164)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(206, 'Purple', 'Foldable Laptop Stand', 165)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(207, 'Orange', 'Wireless Charging Pad', 166)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(208, 'Pink', 'Bluetooth Speaker with Built-in Mic', 167)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(209, 'Silver', 'HD Webcam with Microphone', 168)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(210, 'Gold', 'Smartwatch with Fitness Tracker', 169)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(211, 'Brown', 'Leather Wallet with RFID Blocking', 170)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(212, 'Gray', 'Noise Cancelling Headphones', 171)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(213, 'Beige', 'Electric Toothbrush with Timer', 171)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(214, 'Cyan', 'Smart Wi-Fi Plug with Energy Monitoring', 171)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(215, 'Magenta', 'Wireless Keyboard and Mouse Combo', 174)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(216, 'Turquoise', 'Portable Solar Charger', 171)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(217, 'Indigo', 'Glass Screen Protector for Smartphone', 151)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(218, 'Maroon', 'Portable Bluetooth Printer', 152)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(219, 'Lime', 'Mini Wireless Earbuds', 153)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(220, 'Teal', 'Universal Laptop Charger', 154)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(221, 'Navy', 'Desk Organizer with USB Hub', 151)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(222, 'Burgundy', 'Smartphone Gimbal Stabilizer', 156)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(223, 'Olive', 'Bluetooth Car Kit with FM Transmitter', 151)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(224, 'Violet', 'USB-C Hub with Ethernet Adapter', 158)
INTO ITEMDESCRIPTIONS (ITEMID, COLOUR, SPECIFICATIONS, SUPPLIERID) VALUES
(225, 'Khaki', 'Portable Power Bank with Quick Charge', 159)
SELECT * FROM dual;


// INVENTORYLEVELS DATA
INSERT ALL
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(201, 63, 100, 5)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(201, 72, 75, 8)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(201, 56, 200, 14)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(204, 51, 50, 3)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(204, 73, 300, 10)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(204, 68, 150, 7)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(204, 69, 80, 2)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(208, 54, 175, 6)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(209, 59, 120, 9)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(210, 52, 250, 12)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(211, 70, 90, 4)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(212, 62, 180, 11)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(213, 74, 220, 15)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(214, 64, 70, 1)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(214, 66, 190, 16)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(214, 67, 40, 13)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(214, 58, 270, 18)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(218, 71, 110, 20)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(219, 57, 130, 22)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(220, 53, 200, 25)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(221, 75, 85, 17)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(222, 65, 160, 21)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(223, 55, 95, 19)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(224, 60, 140, 23)
INTO INVENTORYLEVELS (ITEMID, STOREID, QUANTITY, AISLE) VALUES
(225, 61, 180, 24)
SELECT * FROM dual;


// EMPLOYEEPERFORMANCE DATA
INSERT ALL
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(251, 125, 4, 'Very helpful and knowledgeable.', TO_DATE('2024/01/05', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(252, 115, 5, 'Excellent service, went above and beyond.', TO_DATE('2024/02/12', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(253, 122, 3, 'Could improve on communication.', TO_DATE('2024/03/20', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(254, 110, 5, 'Always friendly and efficient.', TO_DATE('2024/01/08', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(255, 104, 2, 'Needs to work on time management.', TO_DATE('2024/02/15', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(256, 118, 4, 'Consistently meets expectations.', TO_DATE('2024/03/22', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(257, 107, 5, 'Outstanding performance.', TO_DATE('2024/01/30', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(258, 124, 3, 'Requires more attention to detail.', TO_DATE('2024/02/16', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(259, 124, 4, 'Great team player.', TO_DATE('2024/03/03', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(260, 124, 5, 'Always willing to assist.', TO_DATE('2024/01/20', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(261, 105, 2, 'Could improve on problem-solving skills.', TO_DATE('2024/02/07', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(262, 119, 4, 'Handles difficult situations well.', TO_DATE('2024/03/25', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(263, 109, 5, 'Excellent performance, highly recommended.', TO_DATE('2024/01/13', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(264, 117, 4, 'Consistently exceeds expectations.', TO_DATE('2024/02/29', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(265, 124, 3, 'Needs to improve punctuality.', TO_DATE('2024/03/17', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(266, 114, 5, 'Exceptional performance.', TO_DATE('2024/01/05', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(267, 121, 4, 'Consistently delivers high-quality work.', TO_DATE('2024/02/12', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(268, 101, 3, 'Needs to improve communication with team members.', TO_DATE('2024/03/20', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(269, 103, 5, 'Exemplary performance, goes above and beyond.', TO_DATE('2024/01/08', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(270, 106, 4, 'Great problem-solving skills.', TO_DATE('2024/02/15', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(271, 111, 3, 'Could improve time management.', TO_DATE('2024/03/22', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(272, 113, 5, 'Consistently provides excellent service.', TO_DATE('2024/01/30', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(273, 116, 4, 'Handles customer complaints effectively.', TO_DATE('2024/02/16', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(274, 120, 3, 'Needs to work on attention to detail.', TO_DATE('2024/03/03', 'YYYY/MM/DD'))
INTO EMPLOYEEPERFORMANCE (EMPLOYEEREVIEWID, EMPLOYEEID, RATINGVALUE, REVIEW, REVIEWDATE) VALUES
(275, 120, 5, 'Highly reliable and efficient.', TO_DATE('2024/01/20', 'YYYY/MM/DD'))
SELECT * FROM dual;

// PURCHASEHISTORY DATA
INSERT ALL
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(301, 1, 51, 201, TO_DATE('2024/01/05', 'YYYY/MM/DD'), 3, 25.00, 101)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(302, 3, 52, 202, TO_DATE('2024/02/12', 'YYYY/MM/DD'), 2, 30.50, 102)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(303, 3, 53, 202, TO_DATE('2024/03/20', 'YYYY/MM/DD'), 1, 15.75, 103)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(304, 3, 54, 202, TO_DATE('2024/01/08', 'YYYY/MM/DD'), 4, 45.20, 104)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(305, 5, 55, 202, TO_DATE('2024/02/15', 'YYYY/MM/DD'), 2, 12.99, 105)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(306, 6, 56, 202, TO_DATE('2024/03/22', 'YYYY/MM/DD'), 3, 19.99, 106)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(307, 7, 57, 207, TO_DATE('2024/01/30', 'YYYY/MM/DD'), 1, 29.75, 106)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(308, 8, 58, 209, TO_DATE('2024/02/16', 'YYYY/MM/DD'), 5, 50.00, 106)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(309, 9, 59, 209, TO_DATE('2024/03/03', 'YYYY/MM/DD'), 2, 35.50, 106)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(310, 10, 60, 210, TO_DATE('2024/01/20', 'YYYY/MM/DD'), 4, 40.25, 110)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(311, 11, 61, 211, TO_DATE('2024/02/07', 'YYYY/MM/DD'), 1, 9.99, 111)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(312, 12, 62, 212, TO_DATE('2024/03/25', 'YYYY/MM/DD'), 3, 60.00, 111)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(313, 3, 63, 213, TO_DATE('2024/01/13', 'YYYY/MM/DD'), 2, 15.00, 112)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(314, 18, 64, 214, TO_DATE('2024/02/29', 'YYYY/MM/DD'), 5, 75.50, 114)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(315, 15, 65, 215, TO_DATE('2024/03/17', 'YYYY/MM/DD'), 1, 20.00, 114)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(316, 16, 66, 216, TO_DATE('2024/01/05', 'YYYY/MM/DD'), 4, 30.75, 114)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(317, 17, 67, 217, TO_DATE('2024/02/12', 'YYYY/MM/DD'), 2, 22.99, 117)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(318, 18, 68, 213, TO_DATE('2024/03/20', 'YYYY/MM/DD'), 3, 40.00, 114)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(319, 18, 69, 213, TO_DATE('2024/01/08', 'YYYY/MM/DD'), 1, 9.75, 102)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(320, 20, 70, 223, TO_DATE('2024/02/15', 'YYYY/MM/DD'), 2, 17.50, 120)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(321, 21, 71, 221, TO_DATE('2024/03/22', 'YYYY/MM/DD'), 4, 55.00, 121)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(322, 22, 72, 222, TO_DATE('2024/01/30', 'YYYY/MM/DD'), 1, 14.25, 122)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(323, 23, 73, 223, TO_DATE('2024/02/16', 'YYYY/MM/DD'), 3, 35.99, 123)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(324, 23, 74, 224, TO_DATE('2024/03/03', 'YYYY/MM/DD'), 2, 45.00, 124)
INTO PURCHASEHISTORY (PURCHASEID, CUSTOMERID, STOREID, ITEMID, DATEOFPURCHASE, QUANTITY, PRICEOFEACH, EMPLOYEEID) VALUES
(325, 23, 75, 225, TO_DATE('2024/01/20', 'YYYY/MM/DD'), 4, 60.25, 125)
SELECT * FROM dual;
